sudo: required
services:
  - docker

before_install:
  - docker build -t rubensa/docker-react -f Dockerfile.dev .

script:
  - docker run rubensa/docker-react npm run test -- --coverage

deploy:
  provider: heroku
  api_key:
    secure: "$HEROKU_API_KEY"
  app: rubensa-docker-react
  on:
    brach: master